Solicitud de Piti para la liga
DavidAndres6870/heroes pull request #2
Opened 2020-05-24 23:37 UTC by davidandres687

### Modificaciones

Borré a flash

### Adiciones 
Aplicando a la liga

2020-05-24 23:44 UTC, DavidAndres6870 reviewed
Por favor no borren a flash

2020-05-24 23:44 UTC, DavidAndres6870 commented on heroes.md
> -* Flashhh
No quiero que borren a flash

2020-05-24 23:47 UTC, DavidAndres6870 requested changes

2020-05-24 23:47 UTC, DavidAndres6870 commented on heroes.md
> -* Flashhh
no quiero que borren a flash 2

2020-05-24 23:50 UTC, davidandres687 commented on heroes.md
> -* Flashhh
esta bien

2020-05-25 00:33 UTC, DavidAndres6870 approved these changes
Esto esta correcto

2020-05-25 00:34 UTC, merged